In [2]:
import numpy as np
import pandas as pd
import statsmodels
from statsmodels.regression import linear_model
from statsmodels.tsa.arima.model import ARIMA
from arch import arch_model

In [3]:
df = pd.read_csv('../data/air_quality_uci.csv', encoding='cp949')
df.head(3)

,Date,Time,CO,PT08_S1,NMHC,C6H6,PT08_S2,NOx,PT08_S3,NO2,PT08_S4,PT08_S5,T,RH,AH
0,2005-02-16,17:00:00,1.6,1083,-200,7.0,856,252,720,148,1010,975,8.2,41.8,0.4563
1,2005-02-16,18:00:00,2.2,1143,-200,9.5,960,313,641,153,1110,1136,7.4,44.5,0.4582
2,2005-02-16,19:00:00,3.4,1288,-200,15.9,1178,433,539,171,1300,1434,7.0,43.4,0.4366

In [4]:
df.shape

(1000, 15)

In [5]:
df['DateTime'] = df['Date'] + ' ' + df['Time']
df.head(3)

,Date,Time,CO,PT08_S1,NMHC,C6H6,PT08_S2,NOx,PT08_S3,NO2,PT08_S4,PT08_S5,T,RH,AH,DateTime
0,2005-02-16,17:00:00,1.6,1083,-200,7.0,856,252,720,148,1010,975,8.2,41.8,0.4563,2005-02-16 17:00:00
1,2005-02-16,18:00:00,2.2,1143,-200,9.5,960,313,641,153,1110,1136,7.4,44.5,0.4582,2005-02-16 18:00:00
2,2005-02-16,19:00:00,3.4,1288,-200,15.9,1178,433,539,171,1300,1434,7.0,43.4,0.4366,2005-02-16 19:00:00

In [6]:
df['DateTime'][3]

'2005-02-16 20:00:00'

In [7]:
type(df['DateTime'][3])

str

In [8]:
df['DateTimeIndex'] = pd.to_datetime(df['DateTime'])
df.head(3)

,Date,Time,CO,PT08_S1,NMHC,C6H6,PT08_S2,NOx,PT08_S3,NO2,PT08_S4,PT08_S5,T,RH,AH,DateTime,DateTimeIndex
0,2005-02-16,17:00:00,1.6,1083,-200,7.0,856,252,720,148,1010,975,8.2,41.8,0.4563,2005-02-16 17:00:00,2005-02-16 17:00:00
1,2005-02-16,18:00:00,2.2,1143,-200,9.5,960,313,641,153,1110,1136,7.4,44.5,0.4582,2005-02-16 18:00:00,2005-02-16 18:00:00
2,2005-02-16,19:00:00,3.4,1288,-200,15.9,1178,433,539,171,1300,1434,7.0,43.4,0.4366,2005-02-16 19:00:00,2005-02-16 19:00:00

In [9]:
type(df['DateTimeIndex'][3])

pandas._libs.tslibs.timestamps.Timestamp

In [10]:
df = df.set_index(keys=['DateTimeIndex'])

In [11]:
df.head(3)

,Date,Time,CO,PT08_S1,NMHC,C6H6,PT08_S2,NOx,PT08_S3,NO2,PT08_S4,PT08_S5,T,RH,AH,DateTime
DateTimeIndex,,,,,,,,,,,,,,,,
2005-02-16 17:00:00,2005-02-16,17:00:00,1.6,1083,-200,7.0,856,252,720,148,1010,975,8.2,41.8,0.4563,2005-02-16 17:00:00
2005-02-16 18:00:00,2005-02-16,18:00:00,2.2,1143,-200,9.5,960,313,641,153,1110,1136,7.4,44.5,0.4582,2005-02-16 18:00:00
2005-02-16 19:00:00,2005-02-16,19:00:00,3.4,1288,-200,15.9,1178,433,539,171,1300,1434,7.0,43.4,0.4366,2005-02-16 19:00:00

In [12]:
df.isnull().sum()

Date        0
Time        0
CO          0
PT08_S1     0
NMHC        0
C6H6        0
PT08_S2     0
NOx         0
PT08_S3     0
NO2         0
PT08_S4     0
PT08_S5     0
T           0
RH          0
AH          0
DateTime    0
dtype: int64

In [13]:
train_ratio = 0.9
n = len(df)
n_train = int(n*train_ratio)
df_train = df[:n_train]
df_test = df[n_train:]

In [14]:
df.columns

Index(['Date', 'Time', 'CO', 'PT08_S1', 'NMHC', 'C6H6', 'PT08_S2', 'NOx',
       'PT08_S3', 'NO2', 'PT08_S4', 'PT08_S5', 'T', 'RH', 'AH', 'DateTime'],
      dtype='object')

In [15]:
features = ['T', 'AH']
target = 'PT08_S4'

X_tn = df_train[features]
y_tn = df_train[target]
X_te = df_test[features]
y_te = df_test[target]

In [16]:
X_tn

                        T      AH
DateTimeIndex
2005-02-16 17:00:00   8.2  0.4563
2005-02-16 18:00:00   7.4  0.4582
2005-02-16 19:00:00   7.0  0.4366
2005-02-16 20:00:00   6.6  0.4241
2005-02-16 21:00:00   5.9  0.4137
...                   ...     ...
2005-03-26 00:00:00  17.1  1.2926
2005-03-26 01:00:00  16.8  1.3135
2005-03-26 02:00:00  16.6  1.3078
2005-03-26 03:00:00  16.1  1.2955
2005-03-26 04:00:00  16.2  1.3013

[900 rows x 2 columns]

In [17]:
ols_reg = linear_model.OLS(endog=y_tn, exog=X_tn)
ols_model = ols_reg.fit()

In [18]:
ols_model.params

T     92.087713
AH   -87.960934
dtype: float64

In [21]:
ols_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                PT08_S4   R-squared (uncentered):                   0.791
Model:                            OLS   Adj. R-squared (uncentered):              0.791
Method:                 Least Squares   F-statistic:                              1701.
Date:                Mon, 01 Jul 2024   Prob (F-statistic):                   3.95e-306
Time:                        14:40:57   Log-Likelihood:                         -6942.3
No. Observations:                 900   AIC:                                  1.389e+04
Df Residuals:                     898   BIC:                                  1.390e+04
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
T             92.0877      1.590     57.911      0.000      88.967      95.209
AH           -87.9609      3.266    -26.930      0.000     -94.371     -81.550
==============================================================================
Omnibus:                       56.134   Durbin-Watson:                   0.130
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               65.528
Skew:                          -0.622   Prob(JB):                     5.90e-15
Kurtosis:                       3.446   Cond. No.                         2.71
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [19]:
ols_model.predict()

array([ 7.14982671e+02,  6.41145375e+02,  6.06210246e+02,  5.70474673e+02,
        5.06928067e+02,  4.24383377e+02,  5.01211345e+02,  4.62573061e+02,
        4.90744733e+02,  4.90727140e+02,  4.99012322e+02,  4.87094354e+02,
        5.95831594e+02,  5.98250520e+02,  5.52153887e+02,  5.69225627e+02,
        6.70020734e+02,  8.90186820e+02,  7.86788070e+02,  7.59056203e+02,
        7.18254079e+02,  7.73770590e+02,  7.73348377e+02,  7.83287224e+02,
        8.12663961e+02,  7.29758631e+02,  6.55771801e+02,  6.38603304e+02,
        6.38752838e+02,  5.92902495e+02,  6.11012175e+02,  5.92533059e+02,
        5.84045568e+02,  5.38045692e+02,  4.72986159e+02,  5.47016969e+02,
        5.93219155e+02,  5.46700309e+02,  5.46383650e+02,  5.92277973e+02,
        7.30242416e+02,  9.52378827e+02,  9.89002806e+02,  1.04478320e+03,
        1.01961100e+03,  9.66284712e+02,  1.00321655e+03,  1.03107157e+03,
        9.84851788e+02,  8.55137342e+02,  7.44605698e+02,  7.25528449e+02,
        6.97576679e+02,  6.05506559e+02,  4.55949603e+02,  3.37467029e+02,
        2.46223741e+02,  2.46874652e+02,  1.64479496e+02,  1.73829004e+02,
        1.37354559e+02,  1.37205026e+02,  4.51085166e+01,  1.80363567e+01,
        1.55226744e+02,  2.46751507e+02,  3.47335507e+02,  6.41532403e+02,
        9.91043499e+02,  1.22609110e+03,  1.09788958e+03,  1.13752182e+03,
        1.20372485e+03,  1.02828320e+03,  9.63575515e+02,  9.16300206e+02,
        8.51099935e+02,  7.95275561e+02,  8.13077377e+02,  8.19189924e+02,
        7.37815114e+02,  6.71664865e+02,  6.62966267e+02,  7.10267965e+02,
        7.26257786e+02,  6.84954285e+02,  6.66264064e+02,  6.85719545e+02,
        7.59776744e+02,  8.78452831e+02,  9.24778163e+02,  7.80691638e+02,
        6.64829562e+02,  6.75208214e+02,  7.14418244e+02,  7.35404246e+02,
        7.18763514e+02,  6.81972410e+02,  5.98046733e+02,  6.27590595e+02,
        6.56351605e+02,  6.58471464e+02,  6.60063556e+02,  5.62557450e+02,
        5.54509763e+02,  4.67742948e+02,  3.55012281e+02,  3.09311473e+02,
        3.00621671e+02,  2.45685703e+02,  3.27465132e+02,  4.11188499e+02,
        3.65100662e+02,  2.90023117e+02,  5.06002262e+02,  6.46332855e+02,
        6.83994773e+02,  6.84847994e+02,  5.72794626e+02,  5.79302997e+02,
        6.08952412e+02,  4.70574552e+02,  4.33123740e+02,  4.42613987e+02,
        4.55807388e+02,  4.57601791e+02,  5.29125715e+02,  5.20928494e+02,
        3.45152599e+02,  2.99442994e+02,  1.73862712e+02,  2.53847739e+02,
        2.45764867e+02,  2.54692164e+02,  2.54366708e+02,  3.17570266e+02,
        3.63007192e+02,  4.99942492e+02,  7.78299101e+02,  9.91921632e+02,
        7.02122044e+02,  5.37850701e+02,  5.46443746e+02,  6.18425066e+02,
        5.29248860e+02,  4.75016579e+02,  4.58024004e+02,  3.29672952e+02,
        3.37500736e+02,  3.57844623e+02,  3.47809019e+02,  3.29541010e+02,
        3.11026711e+02,  3.02583200e+02,  2.65985609e+02,  2.38156985e+02,
        3.22109050e+02,  3.31256249e+02,  3.57396023e+02,  3.46366460e+02,
        3.36990563e+02,  2.29009786e+02,  2.02201509e+02,  3.02125803e+02,
        4.11408401e+02,  4.66089283e+02,  4.55649058e+02,  4.36800507e+02,
        3.91187660e+02,  3.81811762e+02,  3.81978888e+02,  3.64792799e+02,
        3.28300761e+02,  3.37738231e+02,  3.29778505e+02,  2.37945879e+02,
        4.11364421e+02,  3.09716093e+02,  3.36427613e+02,  2.09853372e+02,
        2.45729683e+02,  2.72370834e+02,  2.90374961e+02,  3.17579062e+02,
        2.98915229e+02,  3.16277240e+02,  3.62057214e+02,  4.42816297e+02,
        5.50849850e+02,  6.62454617e+02,  7.17768817e+02,  6.34784323e+02,
        5.98186732e+02,  5.52547496e+02,  4.98543913e+02,  5.16935068e+02,
        4.87918971e+02,  4.50221869e+02,  4.41452902e+02,  4.21830295e+02,
        4.12999756e+02,  4.04415507e+02,  3.96227083e+02,  3.96534946e+02,
        3.96464577e+02,  4.15357109e+02,  4.24917724e+02,  4.60336638e+02,
        5.06248553e+02,  6.99377663e+02,  9.35208853e+02,  1.14411742e+03,
        9.52307720e+02,  1.00881819e+03,  1.10211976e+03,  1.11117020e+03,
        1.08440591e+03,  8.92094834e+02,  7.44587367e+02,  6.70925993e+02,
        6.24706215e+02,  5.18536695e+02,  4.16580504e+02,  3.80598640e+02,
        3.17720538e+02,  2.63611402e+02,  2.08666638e+02,  1.63300081e+02,
        3.02795044e+02,  3.78101288e+02,  4.80725982e+02,  5.28018884e+02,
        5.73957187e+02,  7.65388651e+02,  8.38284765e+02,  8.56385649e+02,
        8.65049062e+02,  8.55558816e+02,  8.45602377e+02,  7.81114589e+02,
        6.30458122e+02,  5.36971830e+02,  5.75548542e+02,  6.21170186e+02,
        6.12102152e+02,  5.65548122e+02,  4.92229795e+02,  5.29038492e+02,
        4.58473343e+02,  3.75005063e+02,  2.74297917e+02,  2.10496225e+02,
        2.94149223e+02,  1.01882130e+02,  8.26465508e+01,  1.84725887e+02,
        2.94914483e+02,  6.71603293e+02,  9.87964867e+02,  1.12107461e+03,
        9.12166780e+02,  8.82649306e+02,  7.70455201e+02,  7.25352527e+02,
        6.91068309e+02,  5.90378755e+02,  5.17676155e+02,  4.71623503e+02,
        3.88410309e+02,  3.78462666e+02,  3.60185861e+02,  3.32154927e+02,
        3.30193398e+02,  3.31407259e+02,  3.24573433e+02,  3.15813263e+02,
        2.96137879e+02,  2.22907513e+02,  1.95844149e+02,  2.15176485e+02,
        2.15968134e+02,  2.72751282e+02,  2.55969813e+02,  3.13254338e+02,
        3.41821834e+02,  3.15893166e+02,  2.90553836e+02,  2.81089978e+02,
        2.16399881e+02,  1.70215287e+02,  1.24074674e+02,  1.05921014e+02,
        7.04845075e+01,  8.03441897e+01,  7.19270668e+01,  7.02118286e+01,
        4.07735195e+01, -4.15323300e+00, -1.27726660e+01, -2.96684844e+01,
       -4.82707450e+01, -7.63984361e+01, -7.70493470e+01, -4.02142619e+01,
        3.42475567e+01,  2.37667358e+02,  2.65768661e+02,  2.83763991e+02,
        2.64484431e+02,  2.73578853e+02,  2.82215878e+02,  3.56774454e+02,
        3.38224970e+02,  1.53029198e+02,  1.43794038e+02,  1.06906176e+02,
        5.26650993e+01,  3.58132614e+01,  9.76144823e+00,  1.61700424e+00,
       -1.62463844e+01, -2.65810557e+01, -1.22222390e+02, -1.51229691e+02,
       -1.42891733e+02, -1.34254707e+02, -1.43481071e+02, -1.99604512e+02,
       -7.03474624e+01,  3.99123951e+02,  6.68421322e+02,  8.64286017e+02,
        8.37442556e+02,  8.73512381e+02,  9.11948355e+02,  1.07025669e+03,
        1.04986882e+03,  8.18426879e+02,  6.40064933e+02,  5.33262094e+02,
        4.41235954e+02,  4.11762460e+02,  4.29836955e+02,  3.47160324e+02,
        3.73027419e+02,  3.17141473e+02,  2.96683236e+02,  2.73911628e+02,
        2.21464215e+02,  2.08429143e+02,  2.16547199e+02,  2.98326629e+02,
        5.01923090e+02,  6.36748067e+02,  2.78255421e+02,  2.76249912e+02,
        4.33414750e+02,  5.06715484e+02,  4.94674371e+02,  5.19397974e+02,
        5.16363322e+02,  4.50758431e+02,  3.87889125e+02,  3.33955911e+02,
        3.34184609e+02,  3.61450283e+02,  3.44158641e+02,  3.36242895e+02,
        3.18441079e+02,  3.00973515e+02,  3.61582963e+02,  3.65602778e+02,
        3.14158120e+02,  2.86505418e+02,  2.32827291e+02,  2.88018346e+02,
        4.06624065e+02,  5.46506057e+02,  6.44935014e+02,  7.35034810e+02,
        9.43713936e+02,  1.07224091e+03,  1.09569861e+03,  1.04392924e+03,
        1.08107219e+03,  9.39703656e+02,  7.66839268e+02,  7.20258850e+02,
        6.36896124e+02,  5.82830968e+02,  5.55046325e+02,  5.29478297e+02,
        4.45068835e+02,  4.85527911e+02,  4.03053589e+02,  3.57818974e+02,
        3.41107873e+02,  2.38835023e+02,  3.82420170e+02,  4.18322869e+02,
        6.01979325e+02,  8.80036867e+02,  1.15738192e+03,  1.24985667e+03,
        1.18607257e+03,  1.19495588e+03,  1.20471001e+03,  1.15826153e+03,
        1.02185326e+03,  7.36433389e+02,  7.26142698e+02,  6.59042471e+02,
        6.00720007e+02,  5.34816049e+02,  5.35027155e+02,  5.63365952e+02,
        5.91353644e+02,  6.20194558e+02,  6.20546401e+02,  5.80060937e+02,
        4.81077087e+02,  4.85712629e+02,  4.59951087e+02,  4.98290304e+02,
        6.28198264e+02,  8.24221289e+02,  9.91887924e+02,  1.09525149e+03,
        1.32819756e+03,  1.17125263e+03,  1.19033867e+03,  1.07087973e+03,
        1.02323499e+03,  8.93889975e+02,  7.54289458e+02,  6.97708621e+02,
        6.50626825e+02,  5.85294613e+02,  5.23085014e+02,  4.78861949e+02,
        4.58632411e+02,  4.29765848e+02,  4.47928304e+02,  4.34048807e+02,
        3.67062929e+02,  4.36107093e+02,  4.74244000e+02,  5.05986885e+02,
        5.98945411e+02,  7.58230108e+02,  8.54944566e+02,  9.47771151e+02,
        9.11314298e+02,  8.93793957e+02,  8.66088478e+02,  8.64874617e+02,
        8.37336264e+02,  7.01113447e+02,  6.08436396e+02,  5.34009762e+02,
        4.31499417e+02,  3.56712143e+02,  3.28021502e+02,  2.44087029e+02,
        1.96310342e+02,  1.50477592e+02,  5.86361698e+01,  1.22580618e+01,
        9.45916456e+01,  4.87500993e+01, -6.51132449e+00,  4.84598282e+01,
        3.42735889e+02,  6.76952056e+02,  9.74368322e+02,  1.23772027e+03,
        1.26572482e+03,  1.27443221e+03,  1.35775975e+03,  1.49503810e+03,
        1.42884387e+03,  1.18391826e+03,  9.73945371e+02,  8.33984214e+02,
        7.41263183e+02,  6.50512476e+02,  5.68152504e+02,  4.66671302e+02,
        4.11058034e+02,  3.83282187e+02,  3.92446978e+02,  3.09348134e+02,
        1.71075827e+02,  1.43212019e+02,  1.42939340e+02,  2.61413117e+02,
        4.82230114e+02,  7.22335467e+02,  9.23591429e+02,  1.28699888e+03,
        1.39170751e+03,  1.42461953e+03,  1.53393732e+03,  1.56109744e+03,
        1.59795011e+03,  1.28473754e+03,  1.11896207e+03,  9.94691663e+02,
        9.10053503e+02,  8.29584691e+02,  7.02130840e+02,  6.57054554e+02,
        6.30246277e+02,  5.01508197e+02,  3.64810391e+02,  3.09680909e+02,
        3.28617421e+02,  4.30212972e+02,  3.39726148e+02,  3.85110297e+02,
        6.31706428e+02,  1.01785910e+03,  1.29337457e+03,  1.54484373e+03,
        1.68166542e+03,  1.72408677e+03,  1.76553100e+03,  1.83052896e+03,
        1.79138930e+03,  1.48415733e+03,  1.30891874e+03,  1.14913267e+03,
        1.01624209e+03,  8.38681328e+02,  7.27358036e+02,  6.70486927e+02,
        5.86860318e+02,  4.84868942e+02,  4.84182847e+02,  3.63307736e+02,
        4.08946972e+02,  3.72173460e+02,  3.07369013e+02,  3.52744366e+02,
        6.09252956e+02,  9.77612603e+02, -8.25355840e+02,  1.53158070e+03,
        1.57986682e+03,  1.67096937e+03,  1.71920346e+03,  1.67185778e+03,
        1.62482950e+03,  1.41749544e+03,  1.21077710e+03,  1.12415982e+03,
        1.11471355e+03,  1.06012063e+03,  9.13343241e+02,  8.86807643e+02,
        8.78364132e+02,  8.59172533e+02,  8.76041963e+02,  8.82893382e+02,
        8.29196924e+02,  7.70117996e+02,  7.89793380e+02,  9.01855544e+02,
        1.08538885e+03,  1.30872153e+03,  1.23452360e+03,  1.31781596e+03,
        1.59395669e+03,  1.58517892e+03,  1.56825672e+03,  1.55859935e+03,
        1.55194144e+03,  1.37483734e+03,  1.22253600e+03,  1.14730012e+03,
        1.03616155e+03,  1.00265139e+03,  1.03932814e+03,  1.08073646e+03,
        1.06267956e+03,  1.07443040e+03,  1.10289234e+03,  1.14956072e+03,
        1.06260919e+03,  1.15770516e+03,  1.06772851e+03,  1.12241819e+03,
        1.12278763e+03,  1.21423323e+03,  1.17342231e+03,  1.14079981e+03,
        1.22591222e+03,  1.50484058e+03,  1.75860552e+03,  1.74024955e+03,
        1.67822467e+03,  1.43938596e+03,  1.31612711e+03,  1.28806978e+03,
        1.26964344e+03,  1.19016859e+03,  1.14156507e+03,  1.14109888e+03,
        1.00235158e+03,  8.37886726e+02,  8.30094126e+02,  7.47435086e+02,
        7.01048182e+02,  7.74208179e+02,  8.39197344e+02,  9.21293433e+02,
        1.00280898e+03,  1.19030053e+03,  1.43076653e+03,  1.57903046e+03,
        1.70801483e+03,  1.78347940e+03,  1.77468404e+03,  1.79397240e+03,
        1.67505002e+03,  1.58130864e+03,  1.46601831e+03,  1.38878573e+03,
        1.32924940e+03,  1.18115260e+03,  1.08860749e+03,  1.04260761e+03,
        1.11705184e+03,  9.45313348e+02,  8.54272371e+02,  9.95218690e+02,
        8.59998628e+02,  7.86319661e+02,  8.60297695e+02,  8.88143911e+02,
        1.12645486e+03,  1.43774109e+03,  1.68811954e+03,  1.86780090e+03,
        1.97133159e+03,  1.98495600e+03,  2.11464406e+03,  2.11547089e+03,
        2.04034937e+03,  1.80804541e+03,  1.59297152e+03,  1.44198960e+03,
        1.30171179e+03,  1.20226248e+03,  1.14725614e+03,  1.01770882e+03,
        9.81032068e+02,  9.72491800e+02,  9.17846103e+02,  7.62537240e+02,
        6.71593019e+02,  6.25936191e+02,  6.36200494e+02,  7.37329852e+02,
        1.01181618e+03,  1.39775774e+03,  1.70973006e+03,  2.06024392e+03,
        2.34227729e+03,  2.41298392e+03,  2.56167885e+03,  2.60043149e+03,
        2.51838818e+03,  2.16587761e+03,  1.87311374e+03,  1.62270816e+03,
        1.48396087e+03,  1.35791439e+03,  1.24605454e+03,  1.28352294e+03,
        1.15597233e+03,  1.09175723e+03,  9.91226002e+02,  8.62962911e+02,
        8.36286575e+02,  7.63548791e+02,  6.63070343e+02,  8.09355153e+02,
        1.14779271e+03,  1.48840289e+03,  1.84842458e+03,  2.17257876e+03,
        2.39026435e+03,  2.42841005e+03,  2.54654152e+03,  2.49514084e+03,
        2.35560263e+03,  2.03180030e+03,  1.79983060e+03,  1.53236281e+03,
        1.42083721e+03,  1.27994367e+03,  1.19514718e+03,  1.07580259e+03,
        1.03062955e+03,  8.92911394e+02,  7.55650638e+02,  6.92068848e+02,
        6.46851824e+02,  6.01652393e+02,  6.29586570e+02,  7.39942292e+02,
        1.04232761e+03,  1.35324440e+03,  1.66804027e+03,  1.97902744e+03,
        2.20608892e+03,  2.23797254e+03,  2.32166072e+03,  2.29552975e+03,
        2.25111317e+03,  1.97595834e+03,  1.69631750e+03,  1.46747846e+03,
        1.35312932e+03,  1.14412400e+03,  1.03035539e+03,  1.00367026e+03,
        9.86290655e+02,  1.00428599e+03,  1.05022429e+03,  1.03994239e+03,
        1.03087436e+03,  1.00506004e+03,  1.01554425e+03,  1.04166643e+03,
        1.09561723e+03,  1.15043006e+03,  1.25317790e+03,  1.37455438e+03,
        1.53145534e+03,  1.71645760e+03,  1.87359605e+03,  1.91920010e+03,
        1.80721710e+03,  1.59253904e+03,  1.40630533e+03,  1.29531629e+03,
        1.21297391e+03,  1.12863481e+03,  1.15700880e+03,  1.16624396e+03,
        1.16568980e+03,  1.14706995e+03,  1.12934730e+03,  1.11178298e+03,
        1.07601222e+03,  1.12198571e+03,  1.05832475e+03,  1.14155554e+03,
        1.20574426e+03,  1.33559944e+03,  1.48504205e+03,  1.63331477e+03,
        1.90172374e+03,  1.88297195e+03,  2.04829882e+03,  1.95566575e+03,
        1.90028118e+03,  1.69610492e+03,  1.51075961e+03,  1.38602301e+03,
        1.34687456e+03,  1.27273819e+03,  1.18358838e+03,  1.11915336e+03,
        1.13567975e+03,  1.13498486e+03,  1.11585483e+03,  1.03353884e+03,
        9.79781546e+02,  1.10005852e+03,  1.09055948e+03,  1.15632270e+03,
        1.26636176e+03,  1.37494067e+03,  1.59492204e+03,  1.73457534e+03,
        1.90034201e+03,  2.05692631e+03,  2.10637426e+03,  2.01433932e+03,
        2.01536846e+03,  1.84005876e+03,  1.62604041e+03,  1.49344084e+03,
        1.31623118e+03,  1.21531293e+03,  1.18043058e+03,  1.13707833e+03,
        1.07334700e+03,  1.09522141e+03,  1.09639129e+03,  1.02498172e+03,
        8.96674645e+02,  9.24300958e+02,  8.70156638e+02,  1.00593965e+03,
        1.21534006e+03,  1.43499597e+03,  1.77361824e+03,  1.91052715e+03,
        2.07630263e+03,  2.07831693e+03,  2.26798112e+03,  2.27850125e+03,
        2.03795609e+03,  1.88926115e+03,  1.76405763e+03,  1.62611957e+03,
        1.51446203e+03,  1.41722860e+03,  1.40519628e+03,  1.37801857e+03,
        1.34105154e+03,  1.32321454e+03,  1.30402294e+03,  1.23922729e+03,
        1.28449709e+03,  1.21099405e+03,  1.19319223e+03,  1.32099793e+03,
        1.54472643e+03,  1.69317508e+03,  1.88514384e+03,  2.03776258e+03,
        2.15930619e+03,  2.19485779e+03,  2.07140616e+03,  2.08637563e+03,
        2.07871497e+03,  2.02931101e+03,  1.87058047e+03,  1.72553517e+03,
        1.66060758e+03,  1.55967173e+03,  1.46304523e+03,  1.39000838e+03,
        1.31537944e+03,  1.33423679e+03,  1.13232112e+03,  1.15187335e+03,
        1.06831711e+03,  1.11499429e+03,  1.02288898e+03,  1.15970114e+03,
        1.40840833e+03,  1.57310189e+03,  1.59748244e+03,  1.36594153e+03,
        1.51624616e+03,  1.83123628e+03,  2.13239968e+03,  2.02353929e+03,
        1.96025657e+03,  1.87823965e+03,  1.76255349e+03,  1.63855577e+03,
        1.58104255e+03,  1.50303590e+03,  1.46959611e+03,  1.38556414e+03,
        1.29762744e+03,  1.28928949e+03,  1.16836160e+03,  1.13965337e+03,
        1.14927555e+03,  1.15451803e+03,  1.19231188e+03,  1.25443352e+03,
        1.36542256e+03,  1.58535995e+03,  1.77344084e+03,  1.85918731e+03,
        1.77510330e+03,  1.83914249e+03,  1.87380494e+03,  1.89113177e+03,
        1.82645926e+03,  1.77074044e+03,  1.67655046e+03,  1.62117469e+03,
        1.56486653e+03,  1.51798704e+03,  1.51824213e+03,  1.46100159e+03,
        1.43153689e+03,  1.41362072e+03,  1.36865879e+03,  1.37735738e+03])

In [20]:
ols_model.predict(X_te)

DateTimeIndex
2005-03-26 05:00:00    1387.973531
2005-03-26 06:00:00    1370.558743
2005-03-26 07:00:00    1371.579090
2005-03-26 08:00:00    1408.150292
2005-03-26 09:00:00    1489.956110
                          ...
2005-03-30 04:00:00     973.827329
2005-03-30 05:00:00     854.042934
2005-03-30 06:00:00     928.926965
2005-03-30 07:00:00     902.312202
2005-03-30 08:00:00    1030.707234
Length: 100, dtype: float64