In [2]:
import pandas as pd
from pycaret.classification import *

df = pd.read_csv('../data/wine_data.csv')

exp1 = setup(data=df, target='class', session_id=123)

In [3]:
best_model = compare_models()

In [4]:
tuned_model = tune_model(best_model)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

In [5]:
evaluate_model(tuned_model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [6]:
predict_model(tuned_model)

,Alcohol,Malic,Ash,Alcalinity,Magesium,Phenols,Flavanoids,Nonflavanoids,Proanthocyanins,Color,Hue,Dilution,Proline,class,prediction_label,prediction_score
19,13.64,3.10,2.56,15.200000,116,2.70,3.03,0.17,1.66,5.10,0.96,3.36,845,0,0,0.99
28,13.87,1.90,2.80,19.400000,107,2.95,2.97,0.37,1.76,4.50,1.25,3.40,915,0,0,0.95
58,13.72,1.43,2.50,16.700001,108,3.40,3.67,0.19,2.04,6.80,0.89,2.87,1285,0,0,0.96
102,12.34,2.45,2.46,21.000000,98,2.56,2.11,0.34,1.31,2.80,0.80,3.38,438,1,1,0.88
48,14.10,2.02,2.40,18.799999,103,2.75,2.92,0.32,2.38,6.20,1.07,2.75,1060,0,0,0.99
33,13.76,1.53,2.70,19.500000,132,2.95,2.74,0.50,1.35,5.40,1.25,3.00,1235,0,0,0.86
22,13.71,1.86,2.36,16.600000,101,2.61,2.88,0.27,1.69,3.80,1.11,4.00,1035,0,0,0.96
110,11.46,3.74,1.82,19.500000,107,3.18,2.58,0.24,3.58,2.90,0.75,2.81,562,1,1,0.93
162,12.85,3.27,2.58,22.000000,106,1.65,0.60,0.60,0.96,5.58,0.87,2.11,570,2,2,0.89
100,12.08,2.08,1.70,17.500000,97,2.23,2.17,0.26,1.40,3.30,1.27,2.96,710,1,1,0.84
79,12.70,3.87,2.40,23.000000,101,2.83,2.55,0.43,1.95,2.57,1.19,3.13,463,1,1,0.85
117,12.42,1.61,2.19,22.500000,108,2.00,2.09,0.34,1.61,2.06,1.06,2.96,345,1,1,0.93
133,12.70,3.55,2.36,21.500000,106,1.70,1.20,0.17,0.84,5.00,0.78,1.29,600,2,2,0.88
96,11.81,2.12,2.74,21.500000,134,1.60,0.99,0.14,1.56,2.50,0.95,2.26,625,1,1,0.75
142,13.52,3.17,2.72,23.500000,97,1.55,0.52,0.50,0.55,4.35,0.89,2.06,520,2,2,0.85
131,12.88,2.99,2.40,20.000000,104,1.30,1.22,0.24,0.83,5.40,0.74,1.42,530,2,2,0.90
136,12.25,4.72,2.54,21.000000,89,1.38,0.47,0.53,0.80,3.85,0.75,1.27,720,2,2,0.87
25,13.05,2.05,3.22,25.000000,124,2.63,2.68,0.47,1.92,3.58,1.13,3.20,830,0,0,0.65
109,11.61,1.35,2.70,20.000000,94,2.74,2.92,0.29,2.49,2.65,0.96,3.26,680,1,1,0.78
159,13.48,1.67,2.64,22.500000,89,2.60,1.10,0.52,2.29,11.75,0.57,1.78,620,2,2,0.70
85,12.67,0.98,2.24,18.000000,99,2.20,1.94,0.30,1.46,2.62,1.23,3.16,450,1,1,0.95
17,13.83,1.57,2.62,20.000000,115,2.95,3.40,0.40,1.72,6.60,1.13,2.57,1130,0,0,0.95
71,13.86,1.51,2.67,25.000000,86,2.95,2.86,0.21,1.87,3.38,1.36,3.16,410,1,1,0.56
158,14.34,1.68,2.70,25.000000,98,2.80,1.31,0.53,2.70,13.00,0.57,1.96,660,2,2,0.59
2,13.16,2.36,2.67,18.600000,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,0,0,0.96
137,12.53,5.51,2.64,25.000000,96,1.79,0.60,0.63,1.10,5.00,0.82,1.69,515,2,2,0.88
60,12.33,1.10,2.28,16.000000,101,2.05,1.09,0.63,0.41,3.27,1.25,1.67,680,1,1,0.83
115,11.03,1.51,2.20,21.500000,85,2.46,2.17,0.52,2.01,1.90,1.71,2.87,407,1,1,0.99
47,13.90,1.68,2.12,16.000000,101,3.10,3.39,0.21,2.14,6.10,0.91,3.33,985,0,0,0.99
143,13.62,4.95,2.35,20.000000,92,2.00,0.80,0.47,1.02,4.40,0.91,2.05,550,2,2,0.67
125,12.07,2.16,2.17,21.000000,85,2.60,2.65,0.37,1.35,2.76,0.86,3.28,378,1,1,0.97
73,12.99,1.67,2.60,30.000000,139,3.30,2.89,0.21,1.96,3.35,1.31,3.50,985,1,0,0.61
168,13.58,2.58,2.69,24.500000,105,1.55,0.84,0.39,1.54,8.66,0.74,1.80,750,2,2,0.90
38,13.07,1.50,2.10,15.500000,98,2.40,2.64,0.28,1.37,3.70,1.18,2.69,1020,0,0,0.70
45,14.21,4.04,2.44,18.900000,111,2.85,2.65,0.30,1.25,5.24,0.87,3.33,1080,0,0,0.95
9,13.86,1.35,2.27,16.000000,98,2.98,3.15,0.22,1.85,7.22,1.01,3.55,1045,0,0,0.94
52,13.82,1.75,2.42,14.000000,111,3.88,3.74,0.32,1.87,7.05,1.01,3.26,1190,0,0,0.95
65,12.37,1.21,2.56,18.100000,98,2.42,2.65,0.37,2.08,4.60,1.19,2.30,678,1,1,0.56
150,13.50,3.12,2.62,24.000000,123,1.40,1.57,0.22,1.25,8.60,0.59,1.30,500,2,2,0.88
84,11.84,0.89,2.58,18.000000,94,2.20,2.21,0.22,2.35,3.05,0.79,3.08,520,1,1,0.90
34,13.51,1.80,2.65,19.000000,110,2.35,2.53,0.29,1.54,4.20,1.10,2.87,1095,0,0,0.90
175,13.27,4.28,2.26,20.000000,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835,2,2,1.00
77,11.84,2.89,2.23,18.000000,112,1.72,1.32,0.43,0.95,2.65,0.96,2.52,500,1,1,0.85
169,13.40,4.60,2.86,25.000000,112,1.98,0.96,0.27,1.11,8.50,0.67,1.92,630,2,2,0.90
32,13.68,1.83,2.36,17.200001,104,2.42,2.69,0.42,1.97,3.84,1.23,2.87,990,0,0,0.82
114,12.08,1.39,2.50,22.500000,84,2.56,2.29,0.43,1.04,2.90,0.93,3.19,385,1,1,0.95
103,11.82,1.72,1.88,19.500000,86,2.50,1.64,0.37,1.42,2.06,0.94,2.44,415,1,1,1.00
113,11.41,0.74,2.50,21.000000,88,2.48,2.01,0.42,1.44,3.08,1.10,2.31,434,1,1,0.95
14,14.38,1.87,2.38,12.000000,102,3.30,3.64,0.29,2.96,7.50,1.20,3.00,1547,0,0,1.00
177,14.13,4.10,2.74,24.500000,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560,2,2,0.96
42,13.88,1.89,2.59,15.000000,101,3.25,3.56,0.17,1.70,5.43,0.88,3.56,1095,0,0,0.96
108,12.22,1.29,1.94,19.000000,92,2.36,2.04,0.39,2.08,2.70,0.86,3.02,312,1,1,0.97
76,13.03,0.90,1.71,16.000000,86,1.95,2.03,0.24,1.46,4.60,1.19,2.48,392,1,1,0.89
154,12.58,1.29,2.10,20.000000,103,1.48,0.58,0.53,1.40,7.60,0.58,1.55,640,2,2,0.86

In [7]:
final_model = finalize_model(tuned_model)

In [8]:
save_model(final_model, 'wine_model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['Alcohol', 'Malic', 'Ash',
                                              'Alcalinity', 'Magesium',
                                              'Phenols', 'Flavanoids',
                                              'Nonflavanoids', 'Proanthocyanins',
                                              'Color', 'Hue', 'Dilution',
                                              'Proline'],
                                     transformer=SimpleImputer(add_indicator=False,
                                                               copy=True,
                                                               fill_value=None,
                                                               keep_empty_features=False,
                                                               miss...
                  ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0,
                                       class_weight=None, criterion='gini',
                                       max_depth=None, max_features='sqrt',
                                       max_leaf_nodes=None, max_samples=None,
                                       min_impurity_decrease=0.0,
                                       min_samples_leaf=1, min_samples_split=2,
                                       min_weight_fraction_leaf=0.0,
                                       monotonic_cst=None, n_estimators=100,
                                       n_jobs=-1, oob_score=False,
                                       random_state=123, verbose=0,
                                       warm_start=False))],
          verbose=False),
 'wine_model.pkl')

In [10]:
loaded_model = load_model('wine_model')
new_data = df.iloc[20:40, 0:-1]
predictions = predict_model(loaded_model, data=new_data)

Transformation Pipeline and Model Successfully Loaded

In [11]:
predictions

,Alcohol,Malic,Ash,Alcalinity,Magesium,Phenols,Flavanoids,Nonflavanoids,Proanthocyanins,Color,Hue,Dilution,Proline,prediction_label,prediction_score
20,14.06,1.63,2.28,16.000000,126,3.00,3.17,0.24,2.10,5.65,1.09,3.71,780,0,1.0
21,12.93,3.80,2.65,18.600000,102,2.41,2.41,0.25,1.98,4.50,1.03,3.52,770,0,1.0
22,13.71,1.86,2.36,16.600000,101,2.61,2.88,0.27,1.69,3.80,1.11,4.00,1035,0,1.0
23,12.85,1.60,2.52,17.799999,95,2.48,2.37,0.26,1.46,3.93,1.09,3.63,1015,0,1.0
24,13.50,1.81,2.61,20.000000,96,2.53,2.61,0.28,1.66,3.52,1.12,3.82,845,0,1.0
25,13.05,2.05,3.22,25.000000,124,2.63,2.68,0.47,1.92,3.58,1.13,3.20,830,0,1.0
26,13.39,1.77,2.62,16.100000,93,2.85,2.94,0.34,1.45,4.80,0.92,3.22,1195,0,1.0
27,13.30,1.72,2.14,17.000000,94,2.40,2.19,0.27,1.35,3.95,1.02,2.77,1285,0,1.0
28,13.87,1.90,2.80,19.400000,107,2.95,2.97,0.37,1.76,4.50,1.25,3.40,915,0,1.0
29,14.02,1.68,2.21,16.000000,96,2.65,2.33,0.26,1.98,4.70,1.04,3.59,1035,0,1.0
30,13.73,1.50,2.70,22.500000,101,3.00,3.25,0.29,2.38,5.70,1.19,2.71,1285,0,1.0
31,13.58,1.66,2.36,19.100000,106,2.86,3.19,0.22,1.95,6.90,1.09,2.88,1515,0,1.0
32,13.68,1.83,2.36,17.200001,104,2.42,2.69,0.42,1.97,3.84,1.23,2.87,990,0,1.0
33,13.76,1.53,2.70,19.500000,132,2.95,2.74,0.50,1.35,5.40,1.25,3.00,1235,0,1.0
34,13.51,1.80,2.65,19.000000,110,2.35,2.53,0.29,1.54,4.20,1.10,2.87,1095,0,1.0
35,13.48,1.81,2.41,20.500000,100,2.70,2.98,0.26,1.86,5.10,1.04,3.47,920,0,1.0
36,13.28,1.64,2.84,15.500000,110,2.60,2.68,0.34,1.36,4.60,1.09,2.78,880,0,1.0
37,13.05,1.65,2.55,18.000000,98,2.45,2.43,0.29,1.44,4.25,1.12,2.51,1105,0,1.0
38,13.07,1.50,2.10,15.500000,98,2.40,2.64,0.28,1.37,3.70,1.18,2.69,1020,0,1.0
39,14.22,3.99,2.51,13.200000,128,3.00,3.04,0.20,2.08,5.10,0.89,3.53,760,0,1.0

In [13]:
from pycaret.regression import *
df = pd.read_csv('../data/house_prices.csv')

In [14]:
exp_reg = setup(data=df, target='MEDV', session_id=123)

In [30]:
best_model = compare_models()

In [28]:
tuned_model = tune_model(best_model)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

In [18]:
evaluate_model(tuned_model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [19]:
predict_model(tuned_model)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV,prediction_label
410,51.135799,0.0,18.10,0,0.5970,5.757,100.000000,1.4130,24,666,20.200001,2.600000,10.11,15.000000,33.702
85,0.057350,0.0,4.49,0,0.4490,6.630,56.099998,4.4377,3,247,18.500000,392.299988,6.53,26.600000,27.214
280,0.035780,20.0,3.33,0,0.4429,7.820,64.500000,4.6947,5,216,14.900000,387.309998,3.76,45.400002,47.047
422,12.048200,0.0,18.10,0,0.6140,5.648,87.599998,1.9512,24,666,20.200001,291.549988,14.10,20.799999,20.473
199,0.031500,95.0,1.47,0,0.4030,6.975,15.300000,7.6534,3,402,17.000000,396.899994,4.56,34.900002,30.779
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310,2.635480,0.0,9.90,0,0.5440,4.973,37.799999,2.5194,4,304,18.400000,350.450012,12.64,16.100000,20.511
91,0.039320,0.0,3.41,0,0.4890,6.405,73.900002,3.0921,2,270,17.799999,393.549988,8.20,22.000000,22.671
151,1.496320,0.0,19.58,0,0.8710,5.404,100.000000,1.5916,5,403,14.700000,341.600006,13.28,19.600000,17.677
426,12.247200,0.0,18.10,0,0.5840,5.837,59.700001,1.9976,24,666,20.200001,24.650000,15.69,10.200000,15.066
472,3.568680,0.0,18.10,0,0.5800,6.437,75.000000,2.8965,24,666,20.200001,393.369995,14.36,23.200001,19.422

In [20]:
final_model = finalize_model(tuned_model)

In [21]:
save_model(final_model, 'house_model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['CRIM', 'ZN', 'INDUS', 'CHAS',
                                              'NOX', 'RM', 'AGE', 'DIS', 'RAD',
                                              'TAX', 'PTRATIO', 'B', 'LSTAT'],
                                     transformer=SimpleImputer(add_indicator=False,
                                                               copy=True,
                                                               fill_value=None,
                                                               keep_empty_features=False,
                                                               missing_values=nan,
                                                               strategy='mean'))),
                 ('categorical_imputer'...
                  ExtraTreesRegressor(bootstrap=False, ccp_alpha=0.0,
                                      criterion='squared_error', max_depth=None,
                                      max_features=1.0, max_leaf_nodes=None,
                                      max_samples=None,
                                      min_impurity_decrease=0.0,
                                      min_samples_leaf=1, min_samples_split=2,
                                      min_weight_fraction_leaf=0.0,
                                      monotonic_cst=None, n_estimators=100,
                                      n_jobs=-1, oob_score=False,
                                      random_state=123, verbose=0,
                                      warm_start=False))],
          verbose=False),
 'house_model.pkl')

In [22]:
loaded_model = load_model('house_model')

Transformation Pipeline and Model Successfully Loaded

In [23]:
new_data = df.iloc[20:40, 0:-1]
predictions = predict_model(loaded_model, data=new_data)

In [24]:
predictions

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,prediction_label
20,1.25179,0.0,8.14,0,0.538,5.570,98.099998,3.7979,4,307,21.000000,376.570007,21.020000,13.600000
21,0.85204,0.0,8.14,0,0.538,5.965,89.199997,4.0123,4,307,21.000000,392.529999,13.830000,19.600000
22,1.23247,0.0,8.14,0,0.538,6.142,91.699997,3.9769,4,307,21.000000,396.899994,18.719999,15.200000
23,0.98843,0.0,8.14,0,0.538,5.813,100.000000,4.0952,4,307,21.000000,394.540009,19.879999,14.500000
24,0.75026,0.0,8.14,0,0.538,5.924,94.099998,4.3996,4,307,21.000000,394.329987,16.299999,15.600000
25,0.84054,0.0,8.14,0,0.538,5.599,85.699997,4.4546,4,307,21.000000,303.420013,16.510000,13.900000
26,0.67191,0.0,8.14,0,0.538,5.813,90.300003,4.6820,4,307,21.000000,376.880005,14.810000,16.600000
27,0.95577,0.0,8.14,0,0.538,6.047,88.800003,4.4534,4,307,21.000000,306.380005,17.280001,14.800000
28,0.77299,0.0,8.14,0,0.538,6.495,94.400002,4.4547,4,307,21.000000,387.940002,12.800000,18.400000
29,1.00245,0.0,8.14,0,0.538,6.674,87.300003,4.2390,4,307,21.000000,380.230011,11.980000,21.000000
30,1.13081,0.0,8.14,0,0.538,5.713,94.099998,4.2330,4,307,21.000000,360.170013,22.600000,12.700000
31,1.35472,0.0,8.14,0,0.538,6.072,100.000000,4.1750,4,307,21.000000,376.730011,13.040000,14.500000
32,1.38799,0.0,8.14,0,0.538,5.950,82.000000,3.9900,4,307,21.000000,232.600006,27.709999,13.200000
33,1.15172,0.0,8.14,0,0.538,5.701,95.000000,3.7872,4,307,21.000000,358.769989,18.350000,13.100000
34,1.61282,0.0,8.14,0,0.538,6.096,96.900002,3.7598,4,307,21.000000,248.309998,20.340000,13.500000
35,0.06417,0.0,5.96,0,0.499,5.933,68.199997,3.3603,5,279,19.200001,396.899994,9.680000,18.900000
36,0.09744,0.0,5.96,0,0.499,5.841,61.400002,3.3779,5,279,19.200001,377.559998,11.410000,20.000000
37,0.08014,0.0,5.96,0,0.499,5.850,41.500000,3.9342,5,279,19.200001,396.899994,8.770000,21.000000
38,0.17505,0.0,5.96,0,0.499,5.966,30.200001,3.8473,5,279,19.200001,393.429993,10.130000,24.700001
39,0.02763,75.0,2.95,0,0.428,6.595,21.799999,5.4011,3,252,18.299999,395.630005,4.320000,30.799999